name: Firebase function deploy - Develop

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install npm packages
      run: |
        cd Server/functions
        npm install

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
          args: deploy -P develop --only functions
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: Server